### ISSUE TITLE
Spike: Application health checking

### ISSUE THREAD

**Issue by Jammy-Louie** [pivotal-cf/cf-spinnaker-clouddriver#167]
Kubernetes v1 exposes probes for applications liveliness and readiness. Spinnaker takes these indications together with platform indications when determining the health of the SG or instance.

Add these to SG configuration and use to determine application health.

There are also health check options in manifest and there is `cf set-healthcheck` command

**Comment by claymccoy** [comment]
replace by issue spinnaker/spinnaker#3655
