### ISSUE TITLE
Spike: trigger pipelines from new artifact arriving in a bucket

### ISSUE THREAD

**Issue by okundzich** [pivotal-cf/cf-spinnaker-clouddriver#174]
JPMC are not using Jenkins, they will put artifacts into a bucket/some kind of storage. How will they trigger the our current pipeline? What if artifacts have versions in their name?  What do we need to add?

Maybe a solution is a git trigger that also passes the artifact with version number in its name to take from the bucket and deploy. Similar to how we have with Jenkins.

Appengine pipeline is triggered through pub/sub.

Olga to find out how JPMC will trigger the pipelines. Just putting an artifact into a bucket is not sufficient.

**Comment by okundzich** [comment]
Can we start a wiki with howto docs and put this there? Or use team drive for this?

**Comment by jmelchio** [comment]
Documentation added to our Wiki: https://github.com/pivotal-cf-experimental/spinnaker-workstation/wiki/Trigger-a-Spinnaker-pipeline-from-GCS

**Comment by LeoUrzua** [comment]
> Documentation added to our Wiki: https://github.com/pivotal-cf-experimental/spinnaker-workstation/wiki/Trigger-a-Spinnaker-pipeline-from-GCS

This link is not working
