### ISSUE TITLE
Enable authn authz in our k8s spinnaker deploy

### ISSUE THREAD

**Issue by Jammy-Louie** [pivotal-cf/cf-spinnaker-clouddriver#189]
enable oauth and create a github or google client. cd-spinnaker VM. halyard based config. 

We want only people from pivotal.io to be able to login.

**Comment by pivotal-Jammy-Louie** [comment]
Try first on a test environment and then configure Jon's demo cluster.

**Comment by jmelchio** [comment]
#### Update
A pre-requisite for setting up Oauth (or other authentication) for Spinnaker is that you need to turn on TLS for `deck` and `gate`. The work has been done to get the configuration for this through the pipeline but we currently only have self-signed certificates and they are not trusted and therefore produce errors when used in the k8s setup.

Furthermore, we need to have a TLS enabled and publicly accessible `gate` endpoint for the call-backs from the authorizing system (Google in our case) for the setup to function. 

Dave P. mentioned that the latest version of k8s has some new features with regards to TLS support so we can look into this to see if it will help us.

For now the configuration information will be added to our k8s pipeline but it will be partially commented out until we figure out how to deal with certs and other configuration challenges.

**Comment by okundzich** [comment]
Saw a reference to this in spinnaker slack. 
https://docs.armory.io/install-guide/auth/#github-organization-restriction
Ensure that everyone in your organization has their visibility set to Public if they plan to login to Spinnaker:

**Comment by jmelchio** [comment]
We have effectively done all this work in #252. 
Only thing left to put the cherry on top is #253 
Closing this issue.

**Comment by jmelchio** [comment]
I've been enhancing Sameer's docs [here](https://github.com/pivotal-cf-experimental/spinnaker-workstation/blob/master/spinnaker-k8-quickstart/README.md) but I'm not quite done with it. Stu will be out tomorrow and Friday so I should find time for this. We probably should find a better spot for the information.
