### ISSUE TITLE
Deploy pipeline fails without error message

### ISSUE THREAD

**Issue by okundzich** [pivotal-cf/cf-spinnaker-clouddriver#194]
See this pipeline 
http://35.239.72.30:9000/#/applications/demo/executions/configure/8e2d647a-9a46-4b9c-9cfd-7fd40e998045

I configured accounts to get artifacts from as public. Maybe wrong? Still shouldn't fail without a message

This pipeline with gs expected artifacts fails as well
http://35.239.72.30:9000/#/applications/demo/executions/configure/235041cc-d8b7-4441-b828-065c2cb59c3e

**Comment by jmelchio** [comment]
This is now working on our test k8s environment.
<img width="1427" alt="screen shot 2018-10-03 at 9 59 47 am" src="https://user-images.githubusercontent.com/687348/46415397-326a9b00-c6f3-11e8-9fc7-4b220d2307a0.png">
