### ISSUE TITLE
Static file deployment with manifest

### ISSUE THREAD

**Issue by okundzich** [pivotal-cf/cf-spinnaker-clouddriver#201]
We tried .txt, .zip, with and without manifest, with and without specifying buildpack in direct configuration.

All failed.

Once fixed, provide documentation for tutorial to configure this.

**Comment by jmelchio** [comment]
Tested this out with the following results; when we do a deployment of staticfile with a zip file and 'form' configuration the application deploys as expected. This configuration looks like this in that case:
<img width="914" alt="screen shot 2018-10-11 at 10 42 58 am" src="https://user-images.githubusercontent.com/687348/46812405-a4ba2b80-cd42-11e8-8343-bf9049b26ae9.png">

When trying to do the same with a manifest we run into problems and we get the same error as the one that JPMC is reporting:
<img width="929" alt="screen shot 2018-10-11 at 10 42 13 am" src="https://user-images.githubusercontent.com/687348/46812464-c87d7180-cd42-11e8-98ca-bfe9c42b6e6a.png">

The configuration looks like this in that case:
<img width="934" alt="screen shot 2018-10-11 at 10 41 19 am" src="https://user-images.githubusercontent.com/687348/46812488-d206d980-cd42-11e8-9d40-8657a5e3edb6.png">

**Comment by jmelchio** [comment]
After merge of code into mainline code works as CF-CLI with the exception of the ability to point to a directory which is not available when working with web interface. 
#216 will be used as the issue to enhance the documentation to ensure the process of deploying static web resources is well understood by users.
