### ISSUE TITLE
War file deployment

### ISSUE THREAD

**Issue by okundzich** [pivotal-cf/cf-spinnaker-clouddriver#202]
We tried with and without manifest, and with and without specifying buildpack in direct configuration.

All failed.

Once fixed, provide documentation for tutorial to configure this.

**Comment by jmelchio** [comment]
With updates as a result of #213 and #201 War file deployment works both with and without a manifest.

**Comment by mattyg1** [comment]
We have been able to perform a successful deployment of a war file (although obviously still without a manifest).

**Comment by jmelchio** [comment]
Fixes for manifest merged into mainline.
