### ISSUE TITLE
jar file with manifest validate errors

### ISSUE THREAD

**Issue by okundzich** [pivotal-cf/cf-spinnaker-clouddriver#203]
I gave JPMC manifest that contained some parameters that were not applicable to their env. They tried with it and it failed with obscure messages.

They also tried with manifest containing path.

We never were able to deploy with manifest, but maybe it's because of all these errors.

Improve error handling.

Document for tutorial which manifest is needed for jar files.

Error JPMC had:

![image 6](https://user-images.githubusercontent.com/26604045/46549066-d80e3d80-c89e-11e8-97ce-7464d67fbc91.png)

**Comment by jmelchio** [comment]
This seems to be part of the manifest issues were fixing in #213 and #201. We assume that these will be resolved when the fixes are submitted and accepted.

**Comment by jmelchio** [comment]
Fixes for manifest merged into mainline.
