### ISSUE TITLE
remove white space around fields

### ISSUE THREAD

**Issue by okundzich** [pivotal-cf/cf-spinnaker-clouddriver#204]
JPMC specified a buildpack with a white space after it. It was hard to troubleshoot as it was failing with obscure massage.

**Comment by jmelchio** [comment]
After applying fixes for manifest etc. you now get a proper error message.

Opened a chore #225 to look at improvements on free-form input in general.

<img width="891" alt="screen shot 2018-10-17 at 4 14 59 pm" src="https://user-images.githubusercontent.com/687348/47114790-cfb4eb80-d22a-11e8-92d2-86f964f58896.png">
