### ISSUE TITLE
Provide Installation instructions for custom installation of spinnaker

### ISSUE THREAD

**Issue by Jammy-Louie** [pivotal-cf/cf-spinnaker-clouddriver#44]
- [ ] If custom installation of Spinnaker, Instructions on how to translate community instructions for enabling different features into our own.

- [ ] Installation instructions that I can validate before sharing with customers. JPMC asked for an early access to implementation and will evaluate early alphas. JPMC running Armory based Spinnaker installation (I think it's a single VM with configuration in /opt/spinnaker...)

**Comment by okundzich** [comment]
Add this to wiki/team drive - how to setup spinnaker with our yaml.
